### ISSUE TITLE
`gift` is not modified anywhere, but not marked `constant`

### ISSUE THREAD

**Issue by veox** [joeb000/HappyBirthdayEth#1]
On line 5:

```
uint gift = 1 ether;
```

`gift` is not marked [constant](http://solidity.readthedocs.io/en/latest/contracts.html#constants), so the compiler puts it in storage, increasing dapp creation cost.

**Comment by joeb000** [comment]
awesome, thank you for noting that! will update it today. i appreciate you taking the time to help me out!
