### ISSUE TITLE
Looping over an array is (increasingly) expensive

### ISSUE THREAD

**Issue by veox** [joeb000/HappyBirthdayEth#2]
Iterating over a dynamically-sized array is poor practice.

```
address[] public giftPaid;
mapping (address=>string) public guestList;

modifier newGuestOnly(){
    for (uint i; i < giftPaid.length; i++){
        if (msg.sender==giftPaid[i])
            throw;
    }
    _
}
```

Why not make `giftPaid` a `mapping`, too? It would reduce the cost of running the modifier, and prevent the cost from getting bigger with the array growing.

```
struct Guest {
    string name;  // expensive :(
    bool giftPaid;
}
mapping (address => Guest) public guestList;

modifier newGuestOnly() {
    if (guestList[msg.sender].giftPaid) throw;
    _
}
```

Of course, that would require modifying the rest of the dapp, too.

**Comment by joeb000** [comment]
yep, thats much cleaner, thanks for the advice! I'm updating now to address this issue as well as the other issue you opened. Again, I appreciate you taking the time to give me some constructive feedback!
